CREATE FACT TABLE IF NOT EXISTS "persistent_query_history" (
  engine_name TEXT,
  engine_id TEXT,
  account_name TEXT,
  user_name TEXT,
  login_name TEXT,
  service_account_name TEXT,
  submitted_time TIMESTAMP,
  start_time TIMESTAMP,
  end_time TIMESTAMP,
  duration_us BIGINT,
  status TEXT,
  request_id TEXT,
  query_id TEXT,
  query_label TEXT,
  query_text TEXT,
  query_text_normalized TEXT,
  query_text_normalized_hash TEXT,
  error_message TEXT,
  scanned_rows BIGINT,
  scanned_bytes BIGINT,
  inserted_rows BIGINT,
  inserted_bytes BIGINT,
  spilled_bytes BIGINT,
  returned_rows BIGINT,
  returned_bytes BIGINT,
  time_in_queue_us BIGINT,
  retries BIGINT,
  proxy_time_us BIGINT,
  source_file_name TEXT NOT NULL,
  source_file_timestamp TIMESTAMP NOT NULL
) PRIMARY INDEX
start_time,
engine_name,
query_id,
user_id;
