create fact table if not exists "persistent_query_history" (
  engine_name TEXT,
  engine_id TEXT,
  packdb_version TEXT,
  user_id TEXT,
  account_id TEXT,
  organization_name TEXT,
  start_time TIMESTAMP,
  end_time TIMESTAMP,
  duration_usec BIGINT,
  query_optimization_us BIGINT,
  status TEXT,
  query_id TEXT,
  query_text TEXT,
  query_text_normalized TEXT,
  query_text_normalized_hash TEXT,
  error_message TEXT,
  scanned_rows BIGINT,
  scanned_bytes BIGINT,
  scanned_bytes_cache BIGINT,
  scanned_bytes_storage BIGINT,
  inserted_rows BIGINT,
  inserted_bytes BIGINT,
  inserted_bytes_storage BIGINT,
  spilled_bytes_compressed BIGINT,
  spilled_bytes_uncompressed BIGINT,
  total_ram_consumed BIGINT,
  cpu_usage_us BIGINT,
  cpu_delay_us BIGINT,
  returned_rows BIGINT,
  returned_bytes BIGINT,
  time_in_queue_ms BIGINT,
  rows_total BIGINT,
  start_date pgdate
) primary index start_date,
engine_name,
query_id,
user_id;

insert into customer_query_history_craftable_us_west_2
select *, to_date(start_time) from ex_customer_query_history_craftable_us_west_2;
